[package]
name = "treasury-guest"
version = "0.1.0"
edition = "2024"

[workspace]

[[bin]]
name = "treasury"
path = "src/bin/treasury.rs"

[dependencies]
treasury_core = { path = "../../treasury_core" }
treasury_program = { path = "../../treasury_program" }
nssa_core.workspace = true
risc0-zkvm.workspace = true
borsh.workspace = true
